apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: cse239fall2025
  labels:
    app: grafana
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      uid: prometheus
      isDefault: true
      editable: false
      jsonData:
        timeInterval: "10s"
        queryTimeout: "60s"

