---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-soak-script
  namespace: cse239fall2025
data:
  soak-test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    import { Rate, Trend, Counter } from 'k6/metrics';

    const errorRate = new Rate('errors');
    const requestDuration = new Trend('request_duration');
    const successfulRequests = new Counter('successful_requests');

    const BASE_URL = 'http://nginx-thrift:8080';

    export const options = {
      stages: [
        { duration: '2m', target: 75 },
        { duration: '26m', target: 75 },
        { duration: '2m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<500', 'p(99)<1000'],
        errors: ['rate<0.05'],
      },
    };

    function randomUserId() {
      return Math.floor(Math.random() * 962) + 1;
    }

    function randomString(length) {
      const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ';
      let result = '';
      for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
      }
      return result;
    }

    export default function () {
      const userId = randomUserId();
      const scenario = Math.random();
      
      let response;
      if (scenario < 0.5) {
        response = http.get(`${BASE_URL}/wrk2-api/home-timeline/read?user_id=${userId}&start=0&stop=10`);
      } else if (scenario < 0.8) {
        response = http.get(`${BASE_URL}/wrk2-api/user-timeline/read?user_id=${userId}&start=0&stop=10`);
      } else if (scenario < 0.95) {
        const postText = randomString(100);
        response = http.post(
          `${BASE_URL}/wrk2-api/post/compose`,
          `user_id=${userId}&username=user_${userId}&text=${encodeURIComponent(postText)}&media_ids=[]&media_types=[]&post_type=0`,
          { headers: { 'Content-Type': 'application/x-www-form-urlencoded' }}
        );
      } else {
        response = http.post(
          `${BASE_URL}/wrk2-api/user/follow`,
          `user_id=${userId}&followee_id=${randomUserId()}`,
          { headers: { 'Content-Type': 'application/x-www-form-urlencoded' }}
        );
      }
      
      requestDuration.add(response.timings.duration);
      const success = check(response, { 'status is 200': (r) => r.status === 200 });
      if (success) successfulRequests.add(1);
      errorRate.add(!success);
      sleep(Math.random() * 3 + 1);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-soak-test
  namespace: cse239fall2025
  labels:
    app: k6-soak-test
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: k6-soak-test
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/soak-test.js"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-soak-script

