---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-spike-script
  namespace: cse239fall2025
data:
  spike-test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    import { Rate, Counter } from 'k6/metrics';

    const errorRate = new Rate('errors');
    const successfulRequests = new Counter('successful_requests');
    const BASE_URL = 'http://nginx-thrift:8080';

    export const options = {
      stages: [
        { duration: '1m', target: 50 },
        { duration: '10s', target: 300 },
        { duration: '1m', target: 300 },
        { duration: '10s', target: 50 },
        { duration: '1m', target: 50 },
        { duration: '10s', target: 400 },
        { duration: '1m', target: 400 },
        { duration: '10s', target: 50 },
        { duration: '1m', target: 50 },
        { duration: '10s', target: 500 },
        { duration: '1m', target: 500 },
        { duration: '30s', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<3000'],
        errors: ['rate<0.3'],
      },
    };

    function randomUserId() {
      return Math.floor(Math.random() * 962) + 1;
    }

    export default function () {
      const userId = randomUserId();
      const scenario = Math.random();
      
      let response;
      if (scenario < 0.5) {
        response = http.get(`${BASE_URL}/wrk2-api/home-timeline/read?user_id=${userId}&start=0&stop=10`);
      } else if (scenario < 0.8) {
        response = http.get(`${BASE_URL}/wrk2-api/user-timeline/read?user_id=${userId}&start=0&stop=10`);
      } else {
        response = http.post(
          `${BASE_URL}/wrk2-api/post/compose`,
          `user_id=${userId}&username=user_${userId}&text=SpikeTest&media_ids=[]&media_types=[]&post_type=0`,
          { headers: { 'Content-Type': 'application/x-www-form-urlencoded' }}
        );
      }
      
      const success = check(response, { 'status is 200': (r) => r.status === 200 });
      if (success) successfulRequests.add(1);
      errorRate.add(!success);
      sleep(0.1);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-spike-test
  namespace: cse239fall2025
  labels:
    app: k6-spike-test
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: k6-spike-test
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/spike-test.js"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-spike-script

